using System;
using System.Collections.Generic;
using Tsapi;

namespace TSapiDLL {
	public static class EventDefs {
		public enum EventClass : ushort {
			ACSREQUEST = 0,
			ACSUNSOLICITED = 1,
			ACSCONFIRMATION = 2,
			CSTAREQUEST = 3,
			CSTAUNSOLICITED = 4,
			CSTACONFIRMATION = 5,
			CSTAEVENTREPORT = 6
		}

		public enum EventCstaType : ushort {
			CSTA_ALTERNATE_CALL = 1,
			CSTA_ALTERNATE_CALL_CONF = 2,
			CSTA_ANSWER_CALL = 3,
			CSTA_ANSWER_CALL_CONF = 4,
			CSTA_CALL_COMPLETION = 5,
			CSTA_CALL_COMPLETION_CONF = 6,
			CSTA_CLEAR_CALL = 7,
			CSTA_CLEAR_CALL_CONF = 8,
			CSTA_CLEAR_CONNECTION = 9,
			CSTA_CLEAR_CONNECTION_CONF = 10,
			CSTA_CONFERENCE_CALL = 11,
			CSTA_CONFERENCE_CALL_CONF = 12,
			CSTA_CONSULTATION_CALL = 13,
			CSTA_CONSULTATION_CALL_CONF = 14,
			CSTA_DEFLECT_CALL = 15,
			CSTA_DEFLECT_CALL_CONF = 16,
			CSTA_PICKUP_CALL = 17,
			CSTA_PICKUP_CALL_CONF = 18,
			CSTA_GROUP_PICKUP_CALL = 19,
			CSTA_GROUP_PICKUP_CALL_CONF = 20,
			CSTA_HOLD_CALL = 21,
			CSTA_HOLD_CALL_CONF = 22,
			CSTA_MAKE_CALL = 23,
			CSTA_MAKE_CALL_CONF = 24,
			CSTA_MAKE_PREDICTIVE_CALL = 25,
			CSTA_MAKE_PREDICTIVE_CALL_CONF = 26,
			CSTA_QUERY_MWI = 27,
			CSTA_QUERY_MWI_CONF = 28,
			CSTA_QUERY_DND = 29,
			CSTA_QUERY_DND_CONF = 30,
			CSTA_QUERY_FWD = 31,
			CSTA_QUERY_FWD_CONF = 32,
			CSTA_QUERY_AGENT_STATE = 33,
			CSTA_QUERY_AGENT_STATE_CONF = 34,
			CSTA_QUERY_LAST_NUMBER = 35,
			CSTA_QUERY_LAST_NUMBER_CONF = 36,
			CSTA_QUERY_DEVICE_INFO = 37,
			CSTA_QUERY_DEVICE_INFO_CONF = 38,
			CSTA_RECONNECT_CALL = 39,
			CSTA_RECONNECT_CALL_CONF = 40,
			CSTA_RETRIEVE_CALL = 41,
			CSTA_RETRIEVE_CALL_CONF = 42,
			CSTA_SET_MWI = 43,
			CSTA_SET_MWI_CONF = 44,
			CSTA_SET_DND = 45,
			CSTA_SET_DND_CONF = 46,
			CSTA_SET_FWD = 47,
			CSTA_SET_FWD_CONF = 48,
			CSTA_SET_AGENT_STATE = 49,
			CSTA_SET_AGENT_STATE_CONF = 50,
			CSTA_TRANSFER_CALL = 51,
			CSTA_TRANSFER_CALL_CONF = 52,
			CSTA_UNIVERSAL_FAILURE_CONF = 53,
			CSTA_CALL_CLEARED = 54,
			CSTA_CONFERENCED = 55,
			CSTA_CONNECTION_CLEARED = 56,
			CSTA_DELIVERED = 57,
			CSTA_DIVERTED = 58,
			CSTA_ESTABLISHED = 59,
			CSTA_FAILED = 60,
			CSTA_HELD = 61,
			CSTA_NETWORK_REACHED = 62,
			CSTA_ORIGINATED = 63,
			CSTA_QUEUED = 64,
			CSTA_RETRIEVED = 65,
			CSTA_SERVICE_INITIATED = 66,
			CSTA_TRANSFERRED = 67,
			CSTA_CALL_INFORMATION = 68,
			CSTA_DO_NOT_DISTURB = 69,
			CSTA_FORWARDING = 70,
			CSTA_MESSAGE_WAITING = 71,
			CSTA_LOGGED_ON = 72,
			CSTA_LOGGED_OFF = 73,
			CSTA_NOT_READY = 74,
			CSTA_READY = 75,
			CSTA_WORK_NOT_READY = 76,
			CSTA_WORK_READY = 77,
			CSTA_ROUTE_REGISTER_REQ = 78,
			CSTA_ROUTE_REGISTER_REQ_CONF = 79,
			CSTA_ROUTE_REGISTER_CANCEL = 80,
			CSTA_ROUTE_REGISTER_CANCEL_CONF = 81,
			CSTA_ROUTE_REGISTER_ABORT = 82,
			CSTA_ROUTE_REQUEST = 83,
			CSTA_ROUTE_SELECT_REQUEST = 84,
			CSTA_RE_ROUTE_REQUEST = 85,
			CSTA_ROUTE_USED = 86,
			CSTA_ROUTE_END = 87,
			CSTA_ROUTE_END_REQUEST = 88,
			CSTA_ESCAPE_SVC = 89,
			CSTA_ESCAPE_SVC_CONF = 90,
			CSTA_ESCAPE_SVC_REQ = 91,
			CSTA_ESCAPE_SVC_REQ_CONF = 92,
			CSTA_PRIVATE = 93,
			CSTA_PRIVATE_STATUS = 94,
			CSTA_SEND_PRIVATE = 95,
			CSTA_BACK_IN_SERVICE = 96,
			CSTA_OUT_OF_SERVICE = 97,
			CSTA_REQ_SYS_STAT = 98,
			CSTA_SYS_STAT_REQ_CONF = 99,
			CSTA_SYS_STAT_START = 100,
			CSTA_SYS_STAT_START_CONF = 101,
			CSTA_SYS_STAT_STOP = 102,
			CSTA_SYS_STAT_STOP_CONF = 103,
			CSTA_CHANGE_SYS_STAT_FILTER = 104,
			CSTA_CHANGE_SYS_STAT_FILTER_CONF = 105,
			CSTA_SYS_STAT = 106,
			CSTA_SYS_STAT_ENDED = 107,
			CSTA_SYS_STAT_REQ = 108,
			CSTA_REQ_SYS_STAT_CONF = 109,
			CSTA_SYS_STAT_EVENT_SEND = 110,
			CSTA_MONITOR_DEVICE = 111,
			CSTA_MONITOR_CALL = 112,
			CSTA_MONITOR_CALLS_VIA_DEVICE = 113,
			CSTA_MONITOR_CONF = 114,
			CSTA_CHANGE_MONITOR_FILTER = 115,
			CSTA_CHANGE_MONITOR_FILTER_CONF = 116,
			CSTA_MONITOR_STOP = 117,
			CSTA_MONITOR_STOP_CONF = 118,
			CSTA_MONITOR_ENDED = 119,
			CSTA_SNAPSHOT_CALL = 120,
			CSTA_SNAPSHOT_CALL_CONF = 121,
			CSTA_SNAPSHOT_DEVICE = 122,
			CSTA_SNAPSHOT_DEVICE_CONF = 123,
			CSTA_GETAPI_CAPS = 124,
			CSTA_GETAPI_CAPS_CONF = 125,
			CSTA_GET_DEVICE_LIST = 126,
			CSTA_GET_DEVICE_LIST_CONF = 127,
			CSTA_QUERY_CALL_MONITOR = 128,
			CSTA_QUERY_CALL_MONITOR_CONF = 129,
			CSTA_ROUTE_REQUEST_EXT = 130,
			CSTA_ROUTE_USED_EXT = 131,
			CSTA_ROUTE_SELECT_INV_REQUEST = 132,
			CSTA_ROUTE_END_INV_REQUEST = 133
		}

		public enum EventAcsType : ushort {
			ACS_OPEN_STREAM = 1,
			ACS_OPEN_STREAM_CONF = 2,
			ACS_CLOSE_STREAM = 3,
			ACS_CLOSE_STREAM_CONF = 4,
			ACS_ABORT_STREAM = 5,
			ACS_UNIVERSAL_FAILURE_CONF = 6,
			ACS_UNIVERSAL_FAILURE = 7,
			ACS_KEY_REQUEST = 8,
			ACS_KEY_REPLY = 9,
			ACS_NAME_SRV_REQUEST = 10,
			ACS_NAME_SRV_REPLY = 11,
			ACS_AUTH_REPLY = 12,
			ACS_AUTH_REPLY_TWO = 13,
			ACS_SET_HEARTBEAT_INTERVAL = 14,
			ACS_SET_HEARTBEAT_INTERVAL_CONF = 15
		}

		public static Dictionary<EventClass, String> EventClassNames = new Dictionary<EventClass, String> {
			{ EventClass.ACSREQUEST, "is_NOT_defined"},
			{ EventClass.ACSUNSOLICITED, "acsUnsolicited" },
			{ EventClass.ACSCONFIRMATION, "acsConfirmation" },
			{ EventClass.CSTAREQUEST, "cstaRequest" },
			{ EventClass.CSTAUNSOLICITED, "cstaUnsolicited" },
			{ EventClass.CSTACONFIRMATION, "cstaConfirmation" },
			{ EventClass.CSTAEVENTREPORT, "cstaEventReport" }

		};

		public static Dictionary<EventAcsType, Type> AcsEventTypes = new Dictionary<EventAcsType, Type> {
			{ EventAcsType.ACS_OPEN_STREAM_CONF, typeof(Acs.ACSOpenStreamConfEvent_t) },
			{ EventAcsType.ACS_CLOSE_STREAM_CONF, typeof(Acs.ACSCloseStreamConfEvent_t) },
			{ EventAcsType.ACS_UNIVERSAL_FAILURE_CONF, typeof(Acs.ACSUniversalFailureConfEvent_t) },
			{ EventAcsType.ACS_UNIVERSAL_FAILURE, typeof(Acs.ACSUniversalFailureEvent_t) },
		};

		public static Dictionary<EventAcsType, String> AcsEventNames = new Dictionary<EventAcsType, String> {
			{ EventAcsType.ACS_OPEN_STREAM_CONF, "acsopen" },
			{ EventAcsType.ACS_CLOSE_STREAM_CONF, "acsclose" },
			{ EventAcsType.ACS_UNIVERSAL_FAILURE_CONF, "failureEvent" },
			{ EventAcsType.ACS_UNIVERSAL_FAILURE, "failureEvent" }

		};

		public static Dictionary<EventCstaType, Type> CstaEventTypes = new Dictionary<EventCstaType, Type> {
			{ EventCstaType.CSTA_ALTERNATE_CALL_CONF, typeof(Csta.CSTAAlternateCallConfEvent_t) },
			{ EventCstaType.CSTA_ANSWER_CALL_CONF, typeof(Csta.CSTAAnswerCallConfEvent_t) },
			{ EventCstaType.CSTA_BACK_IN_SERVICE, typeof(Csta.CSTABackInServiceEvent_t) },
			{ EventCstaType.CSTA_CALL_CLEARED, typeof(Csta.CSTACallClearedEvent_t) },
			{ EventCstaType.CSTA_CALL_COMPLETION_CONF, typeof(Csta.CSTACallCompletionConfEvent_t) },
			{ EventCstaType.CSTA_CALL_INFORMATION, typeof(Csta.CSTACallInformationEvent_t) },
			{ EventCstaType.CSTA_CHANGE_MONITOR_FILTER_CONF, typeof(Csta.CSTAChangeMonitorFilterConfEvent_t) },
			{ EventCstaType.CSTA_CHANGE_SYS_STAT_FILTER_CONF, typeof(Csta.CSTAChangeSysStatFilterConfEvent_t) },
			{ EventCstaType.CSTA_CLEAR_CALL_CONF, typeof(Csta.CSTAClearCallConfEvent_t) },
			{ EventCstaType.CSTA_CLEAR_CONNECTION_CONF, typeof(Csta.CSTAClearConnectionConfEvent_t) },
			{ EventCstaType.CSTA_CONFERENCED, typeof(Csta.CSTAConferencedEvent_t) },
			{ EventCstaType.CSTA_CONFERENCE_CALL_CONF, typeof(Csta.CSTAConferenceCallConfEvent_t ) },
			{ EventCstaType.CSTA_CONNECTION_CLEARED, typeof(Csta.CSTAConnectionClearedEvent_t ) },
			{ EventCstaType.CSTA_CONSULTATION_CALL_CONF, typeof(Csta.CSTAConsultationCallConfEvent_t ) },
			{ EventCstaType.CSTA_DEFLECT_CALL_CONF, typeof(Csta.CSTADeflectCallConfEvent_t ) },
			{ EventCstaType.CSTA_DELIVERED, typeof(Csta.CSTADeliveredEvent_t ) },
			{ EventCstaType.CSTA_DIVERTED, typeof(Csta.CSTADivertedEvent_t ) },
			{ EventCstaType.CSTA_DO_NOT_DISTURB, typeof(Csta.CSTADoNotDisturbEvent_t ) },
			{ EventCstaType.CSTA_ESCAPE_SVC_CONF, typeof(Csta.CSTAEscapeSvcConfEvent_t ) },
			{ EventCstaType.CSTA_ESCAPE_SVC_REQ, typeof(Csta.CSTAEscapeSvcReqEvent_t) },
			{ EventCstaType.CSTA_ESTABLISHED, typeof(Csta.CSTAEstablishedEvent_t ) },
			{ EventCstaType.CSTA_FAILED, typeof(Csta.CSTAFailedEvent_t ) },
			{ EventCstaType.CSTA_FORWARDING, typeof(Csta.CSTAForwardingEvent_t ) },
			{ EventCstaType.CSTA_GETAPI_CAPS_CONF, typeof(Csta.CSTAGetAPICapsConfEvent_t ) },
			{ EventCstaType.CSTA_GET_DEVICE_LIST_CONF, typeof(Csta.CSTAGetDeviceListConfEvent_t ) },
			{ EventCstaType.CSTA_GROUP_PICKUP_CALL_CONF, typeof(Csta.CSTAGroupPickupCallConfEvent_t ) },
			{ EventCstaType.CSTA_HELD, typeof(Csta.CSTAHeldEvent_t ) },
			{ EventCstaType.CSTA_HOLD_CALL_CONF, typeof(Csta.CSTAHoldCallConfEvent_t ) },
			{ EventCstaType.CSTA_LOGGED_OFF, typeof(Csta.CSTALoggedOffEvent_t ) },
			{ EventCstaType.CSTA_LOGGED_ON, typeof(Csta.CSTALoggedOnEvent_t ) },
			{ EventCstaType.CSTA_MAKE_CALL_CONF, typeof(Csta.CSTAMakeCallConfEvent_t ) },
			{ EventCstaType.CSTA_MAKE_PREDICTIVE_CALL_CONF, typeof(Csta.CSTAMakePredictiveCallConfEvent_t ) },
			{ EventCstaType.CSTA_MESSAGE_WAITING, typeof(Csta.CSTAMessageWaitingEvent_t ) },
			{ EventCstaType.CSTA_MONITOR_CONF, typeof(Csta.CSTAMonitorConfEvent_t ) },
			{ EventCstaType.CSTA_MONITOR_ENDED, typeof(Csta.CSTAMonitorEndedEvent_t ) },
			{ EventCstaType.CSTA_MONITOR_STOP_CONF, typeof(Csta.CSTAMonitorStopConfEvent_t ) },
			{ EventCstaType.CSTA_NETWORK_REACHED, typeof(Csta.CSTANetworkReachedEvent_t ) },
			{ EventCstaType.CSTA_NOT_READY, typeof(Csta.CSTANotReadyEvent_t ) },
			{ EventCstaType.CSTA_ORIGINATED, typeof(Csta.CSTAOriginatedEvent_t ) },
			{ EventCstaType.CSTA_OUT_OF_SERVICE, typeof(Csta.CSTAOutOfServiceEvent_t ) },
			{ EventCstaType.CSTA_PICKUP_CALL_CONF, typeof(Csta.CSTAPickupCallConfEvent_t ) },
			{ EventCstaType.CSTA_PRIVATE, typeof(Csta.CSTAPrivateEvent_t ) },
			{ EventCstaType.CSTA_PRIVATE_STATUS, typeof(Csta.CSTAPrivateStatusEvent_t ) },
			{ EventCstaType.CSTA_QUERY_AGENT_STATE_CONF, typeof(Csta.CSTAQueryAgentStateConfEvent_t ) },
			{ EventCstaType.CSTA_QUERY_CALL_MONITOR_CONF, typeof(Csta.CSTAQueryCallMonitorConfEvent_t ) },
			{ EventCstaType.CSTA_QUERY_DEVICE_INFO_CONF, typeof(Csta.CSTAQueryDeviceInfoConfEvent_t ) },
			{ EventCstaType.CSTA_QUERY_DND_CONF, typeof(Csta.CSTAQueryDndConfEvent_t ) },
			{ EventCstaType.CSTA_QUERY_FWD_CONF, typeof(Csta.CSTAQueryFwdConfEvent_t ) },
			{ EventCstaType.CSTA_QUERY_LAST_NUMBER_CONF, typeof(Csta.CSTAQueryLastNumberConfEvent_t ) },
			{ EventCstaType.CSTA_QUERY_MWI_CONF, typeof(Csta.CSTAQueryMwiConfEvent_t ) },
			{ EventCstaType.CSTA_QUEUED, typeof(Csta.CSTAQueuedEvent_t ) },
			{ EventCstaType.CSTA_READY, typeof(Csta.CSTAReadyEvent_t ) },
			{ EventCstaType.CSTA_RECONNECT_CALL_CONF, typeof(Csta.CSTAReconnectCallConfEvent_t ) },
			{ EventCstaType.CSTA_REQ_SYS_STAT_CONF, typeof(Csta.CSTAReqSysStatConf_t ) },
			{ EventCstaType.CSTA_RETRIEVED, typeof(Csta.CSTARetrievedEvent_t ) },
			{ EventCstaType.CSTA_RETRIEVE_CALL_CONF, typeof(Csta.CSTARetrieveCallConfEvent_t ) },
			{ EventCstaType.CSTA_ROUTE_END, typeof(Csta.CSTARouteEndEvent_t ) },
			{ EventCstaType.CSTA_ROUTE_REGISTER_ABORT, typeof(Csta.CSTARouteRegisterAbortEvent_t ) },
			{ EventCstaType.CSTA_ROUTE_REGISTER_CANCEL_CONF, typeof(Csta.CSTARouteRegisterCancelConfEvent_t ) },
			{ EventCstaType.CSTA_ROUTE_REGISTER_REQ_CONF, typeof(Csta.CSTARouteRegisterReqConfEvent_t ) },
			{ EventCstaType.CSTA_ROUTE_REQUEST, typeof(Csta.CSTARouteRequestEvent_t ) },
			{ EventCstaType.CSTA_ROUTE_REQUEST_EXT, typeof(Csta.CSTARouteRequestExtEvent_t ) },
			{ EventCstaType.CSTA_ROUTE_USED, typeof(Csta.CSTARouteUsedEvent_t ) },
			{ EventCstaType.CSTA_ROUTE_USED_EXT, typeof(Csta.CSTARouteUsedExtEvent_t ) },
			{ EventCstaType.CSTA_SEND_PRIVATE, typeof(Csta.CSTASendPrivateEvent_t ) },
			{ EventCstaType.CSTA_SERVICE_INITIATED, typeof(Csta.CSTAServiceInitiatedEvent_t ) },
			{ EventCstaType.CSTA_SET_AGENT_STATE_CONF, typeof(Csta.CSTASetAgentStateConfEvent_t ) },
			{ EventCstaType.CSTA_SET_DND_CONF, typeof(Csta.CSTASetDndConfEvent_t ) },
			{ EventCstaType.CSTA_SET_FWD_CONF, typeof(Csta.CSTASetFwdConfEvent_t ) },
			{ EventCstaType.CSTA_SET_MWI_CONF, typeof(Csta.CSTASetMwiConfEvent_t ) },
			{ EventCstaType.CSTA_SNAPSHOT_CALL_CONF, typeof(Csta.CSTASnapshotCallConfEvent_t ) },
			{ EventCstaType.CSTA_SNAPSHOT_DEVICE_CONF, typeof(Csta.CSTASnapshotDeviceConfEvent_t ) },
			{ EventCstaType.CSTA_SYS_STAT_ENDED, typeof(Csta.CSTASysStatEndedEvent_t ) },
			{ EventCstaType.CSTA_SYS_STAT, typeof(Csta.CSTASysStatEvent_t ) },
			{ EventCstaType.CSTA_SYS_STAT_REQ_CONF, typeof(Csta.CSTASysStatReqConfEvent_t ) },
			{ EventCstaType.CSTA_SYS_STAT_REQ, typeof(Csta.CSTASysStatReqEvent_t ) },
			{ EventCstaType.CSTA_SYS_STAT_START_CONF, typeof(Csta.CSTASysStatStartConfEvent_t ) },
			{ EventCstaType.CSTA_SYS_STAT_STOP_CONF, typeof(Csta.CSTASysStatStopConfEvent_t ) },
			{ EventCstaType.CSTA_TRANSFER_CALL_CONF, typeof(Csta.CSTATransferCallConfEvent_t ) },
			{ EventCstaType.CSTA_TRANSFERRED, typeof(Csta.CSTATransferredEvent_t ) },
			{ EventCstaType.CSTA_UNIVERSAL_FAILURE_CONF, typeof(Csta.CSTAUniversalFailureConfEvent_t ) },
			{ EventCstaType.CSTA_WORK_NOT_READY, typeof(Csta.CSTAWorkNotReadyEvent_t ) },
			{ EventCstaType.CSTA_WORK_READY, typeof(Csta.CSTAWorkReadyEvent_t ) },
		};

		public static Dictionary<EventCstaType, String> CstaEventNames = new Dictionary<EventCstaType, String> {
			{ EventCstaType.CSTA_ALTERNATE_CALL_CONF, "alternateCall" },
			{ EventCstaType.CSTA_ANSWER_CALL_CONF, "answerCall" },
			{ EventCstaType.CSTA_BACK_IN_SERVICE, "backInService" },
			{ EventCstaType.CSTA_CALL_CLEARED, "callCleared" },
			{ EventCstaType.CSTA_CALL_COMPLETION_CONF, "callCompletion" },
			{ EventCstaType.CSTA_CALL_INFORMATION, "callInformation" },
			{ EventCstaType.CSTA_CHANGE_MONITOR_FILTER_CONF, "changeMonitorFilter" },
			{ EventCstaType.CSTA_CHANGE_SYS_STAT_FILTER_CONF, "changeSysStatFilter" },
			{ EventCstaType.CSTA_CLEAR_CALL_CONF, "clearCall" },
			{ EventCstaType.CSTA_CLEAR_CONNECTION_CONF, "clearConnection" },
			{ EventCstaType.CSTA_CONFERENCED, "conferenced" },
			{ EventCstaType.CSTA_CONFERENCE_CALL_CONF, "conferenceCall" },
			{ EventCstaType.CSTA_CONNECTION_CLEARED, "connectionCleared" },
			{ EventCstaType.CSTA_CONSULTATION_CALL_CONF, "consultationCall" },
			{ EventCstaType.CSTA_DEFLECT_CALL_CONF, "deflectCall" },
			{ EventCstaType.CSTA_DELIVERED, "delivered" },
			{ EventCstaType.CSTA_DIVERTED, "diverted" },
			{ EventCstaType.CSTA_DO_NOT_DISTURB, "doNotDisturb" },
			{ EventCstaType.CSTA_ESCAPE_SVC_CONF, "escapeService" },
//			{ EventCstaType.CSTA_ESCAPE_SVC_REQ, "" },
			{ EventCstaType.CSTA_ESTABLISHED, "established" },
			{ EventCstaType.CSTA_FAILED, "failed" },
			{ EventCstaType.CSTA_FORWARDING, "forwarding" },
			{ EventCstaType.CSTA_GETAPI_CAPS_CONF, "getAPICaps" },
			{ EventCstaType.CSTA_GET_DEVICE_LIST_CONF, "getDeviceList" },
			{ EventCstaType.CSTA_GROUP_PICKUP_CALL_CONF, "groupPickupCall" },
			{ EventCstaType.CSTA_HELD, "held" },
			{ EventCstaType.CSTA_HOLD_CALL_CONF, "holdCall" },
			{ EventCstaType.CSTA_LOGGED_OFF, "loggedOff" },
			{ EventCstaType.CSTA_LOGGED_ON, "loggedOn" },
			{ EventCstaType.CSTA_MAKE_CALL_CONF, "makeCall" },
			{ EventCstaType.CSTA_MAKE_PREDICTIVE_CALL_CONF, "makePredictiveCall" },
			{ EventCstaType.CSTA_MESSAGE_WAITING, "messageWaiting" },
			{ EventCstaType.CSTA_MONITOR_CONF, "monitorStart" },
			{ EventCstaType.CSTA_MONITOR_ENDED, "monitorEnded" },
			{ EventCstaType.CSTA_MONITOR_STOP_CONF, "monitorStop" },
			{ EventCstaType.CSTA_NETWORK_REACHED, "networkReached" },
			{ EventCstaType.CSTA_NOT_READY, "notReady" },
			{ EventCstaType.CSTA_ORIGINATED, "originated" },
			{ EventCstaType.CSTA_OUT_OF_SERVICE, "outOfService" },
			{ EventCstaType.CSTA_PICKUP_CALL_CONF, "pickupCall" },
			{ EventCstaType.CSTA_PRIVATE, "privateEvent" },
			{ EventCstaType.CSTA_PRIVATE_STATUS, "privateStatus" },
			{ EventCstaType.CSTA_QUERY_AGENT_STATE_CONF, "queryAgentState" },
			{ EventCstaType.CSTA_QUERY_CALL_MONITOR_CONF, "queryCallMonitor" },
			{ EventCstaType.CSTA_QUERY_DEVICE_INFO_CONF, "queryDeviceInfo" },
			{ EventCstaType.CSTA_QUERY_DND_CONF, "queryDnd" },
			{ EventCstaType.CSTA_QUERY_FWD_CONF, "queryFwd" },
			{ EventCstaType.CSTA_QUERY_LAST_NUMBER_CONF, "queryLastNumber"},
			{ EventCstaType.CSTA_QUERY_MWI_CONF, "queryMwi" },
			{ EventCstaType.CSTA_QUEUED, "queued" },
			{ EventCstaType.CSTA_READY, "ready" },
			{ EventCstaType.CSTA_RECONNECT_CALL_CONF, "reconnectCall" },
			{ EventCstaType.CSTA_REQ_SYS_STAT_CONF, "" },
			{ EventCstaType.CSTA_RETRIEVED, "retrieved" },
			{ EventCstaType.CSTA_RETRIEVE_CALL_CONF, "retrieveCall" },
			{ EventCstaType.CSTA_ROUTE_END, "" },
			{ EventCstaType.CSTA_ROUTE_REGISTER_ABORT, "" },
			{ EventCstaType.CSTA_ROUTE_REGISTER_CANCEL_CONF, "routeCancel" },
			{ EventCstaType.CSTA_ROUTE_REGISTER_REQ_CONF, "routeRegister" },
			//{ EventCstaType.CSTA_ROUTE_REQUEST, typeof(Csta.CSTARouteRequestEvent_t ) },
			//{ EventCstaType.CSTA_ROUTE_REQUEST_EXT, typeof(Csta.CSTARouteRequestExtEvent_t ) },
			//{ EventCstaType.CSTA_ROUTE_USED, typeof(Csta.CSTARouteUsedEvent_t ) },
			//{ EventCstaType.CSTA_ROUTE_USED_EXT, typeof(Csta.CSTARouteUsedExtEvent_t ) },
			//{ EventCstaType.CSTA_SEND_PRIVATE, typeof(Csta.CSTASendPrivateEvent_t ) },
			{ EventCstaType.CSTA_SERVICE_INITIATED, "serviceInitiated" },
			{ EventCstaType.CSTA_SET_AGENT_STATE_CONF, "setAgentState" },
			{ EventCstaType.CSTA_SET_DND_CONF, "setDnd" },
			{ EventCstaType.CSTA_SET_FWD_CONF, "setFwd" },
			{ EventCstaType.CSTA_SET_MWI_CONF, "setMwi" },
			{ EventCstaType.CSTA_SNAPSHOT_CALL_CONF, "snapshotCall" },
			{ EventCstaType.CSTA_SNAPSHOT_DEVICE_CONF, "snapshotDevice" },
			//{ EventCstaType.CSTA_SYS_STAT_ENDED, typeof(Csta.CSTASysStatEndedEvent_t ) },
			//{ EventCstaType.CSTA_SYS_STAT, typeof(Csta.CSTASysStatEvent_t ) },
			{ EventCstaType.CSTA_SYS_STAT_REQ_CONF, "sysStatReq" },
			//{ EventCstaType.CSTA_SYS_STAT_REQ, typeof(Csta.CSTASysStatReqEvent_t ) },
			{ EventCstaType.CSTA_SYS_STAT_START_CONF, "sysStatStart" },
			{ EventCstaType.CSTA_SYS_STAT_STOP_CONF, "sysStatStop" },
			{ EventCstaType.CSTA_TRANSFER_CALL_CONF, "transferCall" },
			{ EventCstaType.CSTA_TRANSFERRED, "transferred" },
			{ EventCstaType.CSTA_UNIVERSAL_FAILURE_CONF, "universalFailure" },
			{ EventCstaType.CSTA_WORK_NOT_READY, "workNotReady" },
			{ EventCstaType.CSTA_WORK_READY, "workReady" },
		};

	}
}